selectors:
  less_adam_cache_seed1:
    name: less
    params:
      cache_dir: /jizhicfs/karonhe/dataflex_saves/less_output_seed1
      gradient_type: adam
      proj_dim: 8192
      seed: 123
      save_interval: 16
  less_sgd_cache_seed1:
    name: less
    params:
      cache_dir: /jizhicfs/karonhe/dataflex_saves/less_sgd_output_seed1
      gradient_type: sgd
      proj_dim: 8192
      seed: 123
      save_interval: 16
