selectors:
  less_adam_stem90:
    name: less
    params:
      cache_dir: /jizhicfs/karonhe/dataflex_saves/less_adam_stem90_output
      proj_dim: 8192
      save_interval: 16
      seed: 123
      candidate_subsample: -1
      greedy_device: auto
      gradient_type: adam
      sigma: null
